[package]
name = "core-model-coupling"
version = "0.1.0"
authors = ["calvin"]
build = "src/build.rs"

[lib]
name = "core_model_coupling"
crate-type = ["cdylib"]

[dependencies]
futures = "0.1"
hyper = "0.11"
tokio-core = "0.1"

[build-dependencies]
cbindgen = "0.5.2"